/* Generated by scripts/generate_static_direct_descriptor.py. */
/* Source schedule: miniresnetv2_s1_64x50_tl_int8.11.hal.mlir */
/* Native header: apps/mnist_app/generated_miniresnet/miniresnetv1_s1_64x50_tl_int8.h */
/* Native object: apps/mnist_app/generated_miniresnet/miniresnetv1_s1_64x50_tl_int8.o */
#include "miniresnetv2_s1_64x50_tl_int8_fresh_static_direct_desc.h"

static const ai_static_direct_buffer_base_t miniresnetv2_s1_64x50_tl_int8_fresh_buffer_bases[] = {
    AI_STATIC_DIRECT_BUFFER_INPUT,
    AI_STATIC_DIRECT_BUFFER_OUTPUT,
    AI_STATIC_DIRECT_BUFFER_CONST,
    AI_STATIC_DIRECT_BUFFER_ARENA,
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_0_constants[] = {
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_0_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_INPUT,
        .index = 0u,
        .offset = 0u,
        .length = 3200u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_1_constants[] = {
    3968u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_1_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_2_constants[] = {
    3968u,
    0u,
    208768u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_2_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_3_constants[] = {
    208768u,
    0u,
    267520u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_3_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_4_constants[] = {
    267520u,
    0u,
    13376u,
    53888u,
    55168u,
    280832u,
    0u,
    208u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_4_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_5_constants[] = {
    280832u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_5_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 0u,
        .length = 133120u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_6_constants[] = {
    267520u,
    0u,
    9280u,
    53632u,
    55424u,
    334080u,
    0u,
    208u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_6_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_7_constants[] = {
    334080u,
    0u,
    4288u,
    4224u,
    387328u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_7_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_8_constants[] = {
    387328u,
    0u,
    280832u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_8_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_9_constants[] = {
    280832u,
    0u,
    13312u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_9_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 133120u,
        .length = 404608u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 0u,
        .length = 133120u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_10_constants[] = {
    26624u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_10_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 133120u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 0u,
        .length = 133120u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_11_constants[] = {
    13312u,
    0u,
    79872u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_11_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 133120u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 0u,
        .length = 133120u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_12_constants[] = {
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_12_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 133120u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 133120u,
        .length = 106496u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_13_constants[] = {
    13312u,
    0u,
    53248u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_13_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 133120u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 133120u,
        .length = 106496u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_14_constants[] = {
    13312u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_14_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 133120u,
        .length = 53248u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 186368u,
        .length = 53248u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 2u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 3u,
        .offset = 239616u,
        .length = 111488u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 4u,
        .offset = 239616u,
        .length = 111488u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_15_constants[] = {
    13312u,
    0u,
    5184u,
    53376u,
    93312u,
    26624u,
    0u,
    208u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_15_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 239616u,
        .length = 111488u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 239616u,
        .length = 111488u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_16_constants[] = {
    26624u,
    0u,
    3648u,
    3584u,
    79872u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_16_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 239616u,
        .length = 111488u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 239616u,
        .length = 111488u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_17_constants[] = {
    79872u,
    0u,
    97152u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_17_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 239616u,
        .length = 111488u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 239616u,
        .length = 111488u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_18_constants[] = {
    97152u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_18_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 239616u,
        .length = 111488u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_19_constants[] = {
    3584u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_19_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 239616u,
        .length = 111488u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_20_constants[] = {
    3584u,
    0u,
    7168u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_20_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_21_constants[] = {
    21504u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_21_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_22_constants[] = {
    3584u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_22_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 35840u,
        .length = 28672u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_23_constants[] = {
    14336u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_23_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 35840u,
        .length = 28672u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_24_constants[] = {
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_24_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 14336u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 50176u,
        .length = 14336u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 2u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 3u,
        .offset = 128u,
        .length = 3584u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_25_constants[] = {
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_25_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 128u,
        .length = 3584u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 131264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_26_constants[] = {
    64u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_26_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_27_constants[] = {
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_27_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 128u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_28_constants[] = {
    64u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_28_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 128u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_29_constants[] = {
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_29_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 128u,
        .length = 40u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 192u,
        .length = 4u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_30_constants[] = {
    64u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_30_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_31_constants[] = {
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_31_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 128u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_32_constants[] = {
    64u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_32_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 128u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_33_constants[] = {
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_33_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 128u,
        .length = 40u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 192u,
        .length = 4u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 0u,
        .length = 40u,
        .access = 3u,
    },
};

const ai_static_direct_dispatch_t miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[] = {
    {
        .ordinal = 0u,
        .workgroups = {2u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_0_constants,
        .constant_count = 2u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_0_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 1u,
        .workgroups = {5u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_1_constants,
        .constant_count = 4u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_1_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 2u,
        .workgroups = {5u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_2_constants,
        .constant_count = 6u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_2_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 3u,
        .workgroups = {13u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_3_constants,
        .constant_count = 6u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_3_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 4u,
        .workgroups = {2u, 4u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_4_constants,
        .constant_count = 9u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_4_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 5u,
        .workgroups = {13u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_5_constants,
        .constant_count = 4u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_5_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 4u,
        .workgroups = {2u, 4u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_6_constants,
        .constant_count = 9u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_6_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 6u,
        .workgroups = {13u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_7_constants,
        .constant_count = 8u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_7_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 7u,
        .workgroups = {13u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_8_constants,
        .constant_count = 6u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_8_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 8u,
        .workgroups = {13u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_9_constants,
        .constant_count = 6u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_9_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 9u,
        .workgroups = {13u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_10_constants,
        .constant_count = 4u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_10_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 10u,
        .workgroups = {13u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_11_constants,
        .constant_count = 6u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_11_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 11u,
        .workgroups = {13u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_12_constants,
        .constant_count = 2u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_12_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 12u,
        .workgroups = {13u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_13_constants,
        .constant_count = 6u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_13_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 13u,
        .workgroups = {13u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_14_constants,
        .constant_count = 4u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_14_bindings,
        .binding_count = 5u,
    },
    {
        .ordinal = 4u,
        .workgroups = {2u, 4u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_15_constants,
        .constant_count = 9u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_15_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 6u,
        .workgroups = {13u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_16_constants,
        .constant_count = 8u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_16_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 14u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_17_constants,
        .constant_count = 6u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_17_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 15u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_18_constants,
        .constant_count = 4u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_18_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 16u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_19_constants,
        .constant_count = 4u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_19_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 17u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_20_constants,
        .constant_count = 6u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_20_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 18u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_21_constants,
        .constant_count = 4u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_21_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 19u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_22_constants,
        .constant_count = 4u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_22_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 20u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_23_constants,
        .constant_count = 4u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_23_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 21u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_24_constants,
        .constant_count = 2u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_24_bindings,
        .binding_count = 4u,
    },
    {
        .ordinal = 22u,
        .workgroups = {1u, 1u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_25_constants,
        .constant_count = 2u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_25_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 23u,
        .workgroups = {1u, 1u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_26_constants,
        .constant_count = 4u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_26_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 24u,
        .workgroups = {5u, 1u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_27_constants,
        .constant_count = 2u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_27_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 25u,
        .workgroups = {1u, 1u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_28_constants,
        .constant_count = 4u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_28_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 26u,
        .workgroups = {5u, 1u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_29_constants,
        .constant_count = 2u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_29_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 27u,
        .workgroups = {1u, 1u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_30_constants,
        .constant_count = 4u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_30_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 24u,
        .workgroups = {5u, 1u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_31_constants,
        .constant_count = 2u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_31_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 25u,
        .workgroups = {1u, 1u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_32_constants,
        .constant_count = 4u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_32_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 28u,
        .workgroups = {5u, 1u, 1u},
        .constants = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_33_constants,
        .constant_count = 2u,
        .bindings = miniresnetv2_s1_64x50_tl_int8_fresh_dispatch_33_bindings,
        .binding_count = 3u,
    },
};

const ai_static_direct_command_t miniresnetv2_s1_64x50_tl_int8_fresh_commands[] = {
    {
        .type = AI_STATIC_DIRECT_COMMAND_FILL,
        .config.fill = {
            .target = {
                .base = AI_STATIC_DIRECT_BUFFER_ARENA,
                .index = 0u,
                .offset = 133120u,
                .length = 3920u,
                .access = 2u,
            },
            .pattern = 127u,
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[0],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[1],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_FILL,
        .config.fill = {
            .target = {
                .base = AI_STATIC_DIRECT_BUFFER_ARENA,
                .index = 0u,
                .offset = 341888u,
                .length = 58752u,
                .access = 2u,
            },
            .pattern = 0u,
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[2],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[3],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[4],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[5],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[6],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_FILL,
        .config.fill = {
            .target = {
                .base = AI_STATIC_DIRECT_BUFFER_ARENA,
                .index = 0u,
                .offset = 520448u,
                .length = 17280u,
                .access = 2u,
            },
            .pattern = 128u,
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[7],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[8],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[9],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[10],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[11],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[12],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[13],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[14],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[15],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_FILL,
        .config.fill = {
            .target = {
                .base = AI_STATIC_DIRECT_BUFFER_ARENA,
                .index = 0u,
                .offset = 319488u,
                .length = 17280u,
                .access = 2u,
            },
            .pattern = 128u,
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[16],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[17],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[18],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[19],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[20],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[21],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[22],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[23],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[24],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[25],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[26],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[27],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[28],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[29],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[30],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[31],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[32],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnetv2_s1_64x50_tl_int8_fresh_dispatches[33],
        },
    },
};

const ai_static_direct_descriptor_t miniresnetv2_s1_64x50_tl_int8_fresh_descriptor = {
    .model_name = "miniresnetv2_s1_64x50_tl_int8_fresh",
    .entry_name = "main",
    .input_bytes = 3200u,
    .output_bytes = 0u,
    .const_bytes = 131264u,
    .arena_bytes = 537728u,
    .arena_alignment = 16u,
    .dispatches = miniresnetv2_s1_64x50_tl_int8_fresh_dispatches,
    .dispatch_count = 34u,
    .commands = miniresnetv2_s1_64x50_tl_int8_fresh_commands,
    .command_count = 38u,
    .unsupported_feature_flags = 0u,
    .buffer_bases = miniresnetv2_s1_64x50_tl_int8_fresh_buffer_bases,
    .buffer_base_count = 4u,
};
