/**
 * @file math_compat.c
 * @brief C23 Math Compatibility Functions for picolibc
 * 
 * picolibc (1.8.x) does not include the C23 fmaximum/fminimum series of functions.
 * The difference between these functions and fmax/fmin lies in NaN handling:
 *   - fmax(NaN, x) → x (ignore NaN)
 *   - fmaximum(NaN, x) → NaN (propagate NaN)
 * 
 * Code generated by the IREE compiler uses fmaximumf/fminimumf and requires this compatibility layer.
 */

#include <math.h>

/**
 * @brief C23 fmaximumf - Returns the maximum of two floating-point numbers, propagating NaN
 */
float fmaximumf(float x, float y) {
    /* If either argument is NaN, return NaN */
    if (isnan(x)) return x;
    if (isnan(y)) return y;
    /* Otherwise return the larger value */
    return fmaxf(x, y);
}

/**
 * @brief C23 fminimumf - Returns the minimum of two floating-point numbers, propagating NaN
 */
float fminimumf(float x, float y) {
    if (isnan(x)) return x;
    if (isnan(y)) return y;
    return fminf(x, y);
}

/**
 * @brief C23 fmaximum - double version
 */
double fmaximum(double x, double y) {
    if (isnan(x)) return x;
    if (isnan(y)) return y;
    return fmax(x, y);
}

/**
 * @brief C23 fminimum - double version
 */
double fminimum(double x, double y) {
    if (isnan(x)) return x;
    if (isnan(y)) return y;
    return fmin(x, y);
}
