context:
  version: "1.8.10"
  arch: "rv32"
  target_triple: "riscv32-unknown-elf"
  march: "rv32imafd"
  mabi: "ilp32d"

package:
  name: "picolibc-${{ arch }}"
  version: "${{ version }}"

source:
  # Download specified version from GitHub official release (to avoid repeated compilation issues)
  url: https://github.com/picolibc/picolibc/releases/download/${{ version }}/picolibc-${{ version }}.tar.xz
  sha256: 0ce5ee3bde81256633644d7b3bd25f5a6ccfd8b0590fd4ee543df2c3ede6e27e

build:
  number: 100
  script:
    - |
      # Dynamically generate Meson cross-file (based on Picolibc official recommendation)
      cat > cross_${{ arch }}.txt <<'EOF'
      [binaries]
      c = ['clang', '-target', '${{ target_triple }}', '-mcmodel=medany', '-fuse-ld=lld', '-nostdlib', '-nodefaultlibs']
      ar = 'llvm-ar'
      strip = 'llvm-strip'
      objcopy = 'llvm-objcopy'
      ranlib = 'llvm-ranlib'

      [host_machine]
      system = 'unknown'
      cpu_family = 'riscv32'
      cpu = 'riscv32'
      endian = 'little'

      [properties]
      skip_sanity_check = true

      [built-in options]
      c_args = ['-march=${{ march }}', '-mabi=${{ mabi }}']
      c_link_args = ['-march=${{ march }}', '-mabi=${{ mabi }}']
      EOF

      # Configure Meson (key options refer to official documentation and research results)
      meson setup build \
        --cross-file cross_${{ arch }}.txt \
        --prefix=$PREFIX \
        -Dmultilib=false \
        -Dtests=false \
        -Dpicocrt=true \
        -Dtests-enable-stack-protector=false \
        -Dformat-default=integer \
        -Dthread-local-storage=false

      # Build and install
      ninja -C build install

requirements:
  build:
    - clang >=18
    - lld
    - llvm-tools # Provides llvm-ar, llvm-strip, etc.
    - meson >=0.61
    - ninja
  # host and run left blank (this is a cross-compilation toolchain library)

# Tests temporarily disabled due to rattler-build path matching issues
# tests:
#   - package_contents:
#       files:
#         - "lib/libc.a"

about:
  homepage: https://github.com/picolibc/picolibc
  license: BSD-3-Clause
  summary: "Picolibc C library for ${{ target_triple }}"
