/* Generated by scripts/generate_static_direct_descriptor.py. */
/* Source schedule: miniresnetv1_s1_64x50_tl_int8.11.hal.mlir */
/* Native header: apps/mnist_app/generated_miniresnet/miniresnetv1_s1_64x50_tl_int8.h */
/* Native object: apps/mnist_app/generated_miniresnet/miniresnetv1_s1_64x50_tl_int8.o */
#include "miniresnet_static_direct_desc.h"

static const ai_static_direct_buffer_base_t miniresnet_static_direct_buffer_bases[] = {
    AI_STATIC_DIRECT_BUFFER_INPUT,
    AI_STATIC_DIRECT_BUFFER_OUTPUT,
    AI_STATIC_DIRECT_BUFFER_CONST,
    AI_STATIC_DIRECT_BUFFER_ARENA,
};

static const uint32_t miniresnet_static_direct_dispatch_0_constants[] = {
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_0_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_INPUT,
        .index = 0u,
        .offset = 0u,
        .length = 3200u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_1_constants[] = {
    3968u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_1_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 130240u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_2_constants[] = {
    3968u,
    0u,
    208768u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_2_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 130240u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_3_constants[] = {
    208768u,
    0u,
    267520u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_3_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_4_constants[] = {
    267520u,
    0u,
    4096u,
    280832u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_4_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 130240u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_5_constants[] = {
    280832u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_5_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 130240u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_6_constants[] = {
    267520u,
    0u,
    0u,
    295168u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_6_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 130240u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_7_constants[] = {
    295168u,
    0u,
    309504u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_7_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 130240u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_8_constants[] = {
    309504u,
    0u,
    55680u,
    280832u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_8_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 130240u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_9_constants[] = {
    280832u,
    0u,
    53888u,
    92544u,
    12160u,
    12096u,
    3584u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_9_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 315264u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 130240u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_10_constants[] = {
    0u,
    0u,
    7168u,
    0u,
    2u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_10_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_11_constants[] = {
    3584u,
    0u,
    21504u,
    0u,
    1398511258u,
    32u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_11_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_12_constants[] = {
    0u,
    0u,
    0u,
    0u,
    2u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_12_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 35840u,
        .length = 28672u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_13_constants[] = {
    3584u,
    0u,
    14336u,
    0u,
    1398511258u,
    32u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_13_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 35840u,
        .length = 28672u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_14_constants[] = {
    1096102045u,
    48u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_14_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 14336u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 50176u,
        .length = 14336u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_15_constants[] = {
    56u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_15_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 130240u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 35840u,
        .length = 20096u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_16_constants[] = {
    14336u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_16_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 20096u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 130240u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 35840u,
        .length = 20096u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_17_constants[] = {
    14336u,
    0u,
    93056u,
    0u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_17_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 20096u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 130240u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 35840u,
        .length = 20096u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_18_constants[] = {
    0u,
    0u,
    53376u,
    129920u,
    11520u,
    11456u,
    3584u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_18_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 20096u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 130240u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_19_constants[] = {
    0u,
    0u,
    7168u,
    0u,
    1833982331u,
    34u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_19_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_20_constants[] = {
    3584u,
    0u,
    21504u,
    0u,
    4294967168u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_20_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_21_constants[] = {
    0u,
    0u,
    0u,
    0u,
    1833982331u,
    34u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_21_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 35840u,
        .length = 28672u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_22_constants[] = {
    3584u,
    0u,
    14336u,
    0u,
    4294967168u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_22_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 35840u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 35840u,
        .length = 28672u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_23_constants[] = {
    1073741824u,
    49u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_23_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 35840u,
        .length = 14336u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 50176u,
        .length = 14336u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 128u,
        .length = 3584u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_24_constants[] = {
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_24_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 128u,
        .length = 3584u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_CONST,
        .index = 1u,
        .offset = 0u,
        .length = 130240u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_25_constants[] = {
    64u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_25_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_26_constants[] = {
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_26_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 128u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_27_constants[] = {
    64u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_27_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 128u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_28_constants[] = {
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_28_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 128u,
        .length = 40u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 192u,
        .length = 4u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_29_constants[] = {
    64u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_29_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_30_constants[] = {
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_30_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 128u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_31_constants[] = {
    64u,
    0u,
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_31_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 0u,
        .length = 128u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 128u,
        .length = 128u,
        .access = 3u,
    },
};

static const uint32_t miniresnet_static_direct_dispatch_32_constants[] = {
    1u,
    0u,
};

static const ai_static_direct_slice_t miniresnet_static_direct_dispatch_32_bindings[] = {
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 0u,
        .offset = 128u,
        .length = 40u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 1u,
        .offset = 192u,
        .length = 4u,
        .access = 3u,
    },
    {
        .base = AI_STATIC_DIRECT_BUFFER_ARENA,
        .index = 2u,
        .offset = 0u,
        .length = 40u,
        .access = 3u,
    },
};

const ai_static_direct_dispatch_t miniresnet_static_direct_dispatches[] = {
    {
        .ordinal = 0u,
        .workgroups = {2u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_0_constants,
        .constant_count = 2u,
        .bindings = miniresnet_static_direct_dispatch_0_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 1u,
        .workgroups = {5u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_1_constants,
        .constant_count = 4u,
        .bindings = miniresnet_static_direct_dispatch_1_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 2u,
        .workgroups = {5u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_2_constants,
        .constant_count = 6u,
        .bindings = miniresnet_static_direct_dispatch_2_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 3u,
        .workgroups = {13u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_3_constants,
        .constant_count = 6u,
        .bindings = miniresnet_static_direct_dispatch_3_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 4u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_4_constants,
        .constant_count = 7u,
        .bindings = miniresnet_static_direct_dispatch_4_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 5u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_5_constants,
        .constant_count = 4u,
        .bindings = miniresnet_static_direct_dispatch_5_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 4u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_6_constants,
        .constant_count = 7u,
        .bindings = miniresnet_static_direct_dispatch_6_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 6u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_7_constants,
        .constant_count = 6u,
        .bindings = miniresnet_static_direct_dispatch_7_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 7u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_8_constants,
        .constant_count = 7u,
        .bindings = miniresnet_static_direct_dispatch_8_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 8u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_9_constants,
        .constant_count = 10u,
        .bindings = miniresnet_static_direct_dispatch_9_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 9u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_10_constants,
        .constant_count = 7u,
        .bindings = miniresnet_static_direct_dispatch_10_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 10u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_11_constants,
        .constant_count = 8u,
        .bindings = miniresnet_static_direct_dispatch_11_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 11u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_12_constants,
        .constant_count = 7u,
        .bindings = miniresnet_static_direct_dispatch_12_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 12u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_13_constants,
        .constant_count = 8u,
        .bindings = miniresnet_static_direct_dispatch_13_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 13u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_14_constants,
        .constant_count = 4u,
        .bindings = miniresnet_static_direct_dispatch_14_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 14u,
        .workgroups = {2u, 1u, 1u},
        .constants = miniresnet_static_direct_dispatch_15_constants,
        .constant_count = 2u,
        .bindings = miniresnet_static_direct_dispatch_15_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 15u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_16_constants,
        .constant_count = 4u,
        .bindings = miniresnet_static_direct_dispatch_16_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 7u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_17_constants,
        .constant_count = 7u,
        .bindings = miniresnet_static_direct_dispatch_17_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 8u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_18_constants,
        .constant_count = 10u,
        .bindings = miniresnet_static_direct_dispatch_18_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 10u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_19_constants,
        .constant_count = 8u,
        .bindings = miniresnet_static_direct_dispatch_19_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 9u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_20_constants,
        .constant_count = 7u,
        .bindings = miniresnet_static_direct_dispatch_20_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 12u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_21_constants,
        .constant_count = 8u,
        .bindings = miniresnet_static_direct_dispatch_21_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 11u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_22_constants,
        .constant_count = 7u,
        .bindings = miniresnet_static_direct_dispatch_22_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 13u,
        .workgroups = {7u, 8u, 1u},
        .constants = miniresnet_static_direct_dispatch_23_constants,
        .constant_count = 4u,
        .bindings = miniresnet_static_direct_dispatch_23_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 16u,
        .workgroups = {1u, 1u, 1u},
        .constants = miniresnet_static_direct_dispatch_24_constants,
        .constant_count = 2u,
        .bindings = miniresnet_static_direct_dispatch_24_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 17u,
        .workgroups = {1u, 1u, 1u},
        .constants = miniresnet_static_direct_dispatch_25_constants,
        .constant_count = 4u,
        .bindings = miniresnet_static_direct_dispatch_25_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 18u,
        .workgroups = {5u, 1u, 1u},
        .constants = miniresnet_static_direct_dispatch_26_constants,
        .constant_count = 2u,
        .bindings = miniresnet_static_direct_dispatch_26_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 19u,
        .workgroups = {1u, 1u, 1u},
        .constants = miniresnet_static_direct_dispatch_27_constants,
        .constant_count = 4u,
        .bindings = miniresnet_static_direct_dispatch_27_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 20u,
        .workgroups = {5u, 1u, 1u},
        .constants = miniresnet_static_direct_dispatch_28_constants,
        .constant_count = 2u,
        .bindings = miniresnet_static_direct_dispatch_28_bindings,
        .binding_count = 3u,
    },
    {
        .ordinal = 21u,
        .workgroups = {1u, 1u, 1u},
        .constants = miniresnet_static_direct_dispatch_29_constants,
        .constant_count = 4u,
        .bindings = miniresnet_static_direct_dispatch_29_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 18u,
        .workgroups = {5u, 1u, 1u},
        .constants = miniresnet_static_direct_dispatch_30_constants,
        .constant_count = 2u,
        .bindings = miniresnet_static_direct_dispatch_30_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 19u,
        .workgroups = {1u, 1u, 1u},
        .constants = miniresnet_static_direct_dispatch_31_constants,
        .constant_count = 4u,
        .bindings = miniresnet_static_direct_dispatch_31_bindings,
        .binding_count = 2u,
    },
    {
        .ordinal = 22u,
        .workgroups = {5u, 1u, 1u},
        .constants = miniresnet_static_direct_dispatch_32_constants,
        .constant_count = 2u,
        .bindings = miniresnet_static_direct_dispatch_32_bindings,
        .binding_count = 3u,
    },
};

const ai_static_direct_command_t miniresnet_static_direct_commands[] = {
    {
        .type = AI_STATIC_DIRECT_COMMAND_FILL,
        .config.fill = {
            .target = {
                .base = AI_STATIC_DIRECT_BUFFER_ARENA,
                .index = 0u,
                .offset = 35840u,
                .length = 3920u,
                .access = 2u,
            },
            .pattern = 127u,
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[0],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[1],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_FILL,
        .config.fill = {
            .target = {
                .base = AI_STATIC_DIRECT_BUFFER_ARENA,
                .index = 0u,
                .offset = 244608u,
                .length = 58752u,
                .access = 2u,
            },
            .pattern = 128u,
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[2],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[3],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[4],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[5],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[6],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_FILL,
        .config.fill = {
            .target = {
                .base = AI_STATIC_DIRECT_BUFFER_ARENA,
                .index = 0u,
                .offset = 345344u,
                .length = 5760u,
                .access = 2u,
            },
            .pattern = 128u,
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[7],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[8],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[9],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[10],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[11],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[12],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[13],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[14],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[15],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_FILL,
        .config.fill = {
            .target = {
                .base = AI_STATIC_DIRECT_BUFFER_ARENA,
                .index = 0u,
                .offset = 50176u,
                .length = 5760u,
                .access = 2u,
            },
            .pattern = 128u,
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[16],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[17],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[18],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[19],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[20],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[21],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[22],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[23],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[24],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[25],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[26],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[27],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[28],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[29],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[30],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[31],
        },
    },
    {
        .type = AI_STATIC_DIRECT_COMMAND_DISPATCH,
        .config.dispatch = {
            .dispatch = &miniresnet_static_direct_dispatches[32],
        },
    },
};

const ai_static_direct_descriptor_t miniresnet_static_direct_descriptor = {
    .model_name = "miniresnet_static_direct",
    .entry_name = "main",
    .input_bytes = 3200u,
    .output_bytes = 0u,
    .const_bytes = 130240u,
    .arena_bytes = 351104u,
    .arena_alignment = 16u,
    .dispatches = miniresnet_static_direct_dispatches,
    .dispatch_count = 33u,
    .commands = miniresnet_static_direct_commands,
    .command_count = 37u,
    .unsupported_feature_flags = 0u,
    .buffer_bases = miniresnet_static_direct_buffer_bases,
    .buffer_base_count = 4u,
};
