/* Generated by scripts/generate_static_direct_remap_plan.py. */
#ifndef MINIRESNET_PATCH_ARENA_REMAP_H
#define MINIRESNET_PATCH_ARENA_REMAP_H

#include <stdint.h>

#include "ai_static_direct.h"

#ifdef __cplusplus
extern "C" {
#endif

#define MINIRESNET_PATCH_REMAP_ARENA_BYTES 142336u
#define MINIRESNET_PATCH_REMAP_FIRST_OUTPUT_OFFSET 0u

int miniresnet_patch_invoke_continuation_remapped(
    const ai_static_direct_descriptor_t *descriptor,
    uint32_t command_start,
    const iree_hal_executable_library_v0_t *library,
    const iree_hal_executable_environment_v0_t *environment,
    ai_static_direct_context_t *context);

#ifdef __cplusplus
}
#endif

#endif /* MINIRESNET_PATCH_ARENA_REMAP_H */
