/* Generated by scripts/generate_static_direct_remap_plan.py. */
/* Plan: miniresnet_first_layer_patch */
#include "miniresnet_patch_arena_remap.h"

#include <stddef.h>
#include <stdint.h>

enum {
    MINIRESNET_PATCH_REMAP_MAX_BINDINGS = 8,
    MINIRESNET_PATCH_REMAP_MAX_CONSTANTS = 16,
    MINIRESNET_PATCH_REMAP_OLD_BIG_BINDING_OFFSET = 35840,
    MINIRESNET_PATCH_REMAP_OLD_BIG_BINDING_BYTES = 315264,
    MINIRESNET_PATCH_REMAP_OLD_BIG_INTERNAL_BASE = 208768,
    MINIRESNET_PATCH_REMAP_OLD_BIG_ACTUAL_BASE =
        MINIRESNET_PATCH_REMAP_OLD_BIG_BINDING_OFFSET +
        MINIRESNET_PATCH_REMAP_OLD_BIG_INTERNAL_BASE,
    MINIRESNET_PATCH_REMAP_OLD_ARENA_BYTES = 351104,
    MINIRESNET_PATCH_REMAP_BIG_SUFFIX_BYTES =
        MINIRESNET_PATCH_REMAP_OLD_ARENA_BYTES -
        MINIRESNET_PATCH_REMAP_OLD_BIG_ACTUAL_BASE,
    MINIRESNET_PATCH_REMAP_WORK_BUFFER_OLD_OFFSET = 0,
    MINIRESNET_PATCH_REMAP_WORK_BUFFER_BYTES = 35840,
    MINIRESNET_PATCH_REMAP_WORK_BUFFER_NEW_OFFSET = 106496,
    MINIRESNET_PATCH_REMAP_BIG_SUFFIX_END_COMMAND = 13,
    MINIRESNET_PATCH_REMAP_WORK_BUFFER_END_COMMAND = 17,
};

static int remap_arena_slice(ai_static_direct_slice_t *slice,
                             uint32_t command_index,
                             int *out_big_suffix_binding) {
    if (slice == NULL || out_big_suffix_binding == NULL) {
        return AI_STATIC_DIRECT_ERR_INVALID_ARGUMENT;
    }
    if (slice->base != AI_STATIC_DIRECT_BUFFER_ARENA) {
        return AI_STATIC_DIRECT_OK;
    }
    const uint32_t original_offset = slice->offset;

    if (slice->offset == MINIRESNET_PATCH_REMAP_OLD_BIG_BINDING_OFFSET &&
        slice->length == MINIRESNET_PATCH_REMAP_OLD_BIG_BINDING_BYTES) {
        if (command_index >= MINIRESNET_PATCH_REMAP_BIG_SUFFIX_END_COMMAND) {
            return AI_STATIC_DIRECT_ERR_INVALID_SLICE;
        }
        slice->offset = 0u;
        slice->length = MINIRESNET_PATCH_REMAP_BIG_SUFFIX_BYTES;
        *out_big_suffix_binding = 1;
        return AI_STATIC_DIRECT_OK;
    }

    if (command_index < MINIRESNET_PATCH_REMAP_WORK_BUFFER_END_COMMAND &&
        slice->offset >= MINIRESNET_PATCH_REMAP_WORK_BUFFER_OLD_OFFSET &&
        slice->offset < MINIRESNET_PATCH_REMAP_WORK_BUFFER_BYTES) {
        if (slice->length >
            MINIRESNET_PATCH_REMAP_WORK_BUFFER_BYTES - slice->offset) {
            return AI_STATIC_DIRECT_ERR_INVALID_SLICE;
        }
        slice->offset += MINIRESNET_PATCH_REMAP_WORK_BUFFER_NEW_OFFSET;
        return AI_STATIC_DIRECT_OK;
    }

    if (command_index < MINIRESNET_PATCH_REMAP_BIG_SUFFIX_END_COMMAND &&
        slice->offset >= MINIRESNET_PATCH_REMAP_OLD_BIG_ACTUAL_BASE &&
        slice->offset < MINIRESNET_PATCH_REMAP_OLD_ARENA_BYTES) {
        if (slice->length >
            MINIRESNET_PATCH_REMAP_OLD_ARENA_BYTES - slice->offset) {
            return AI_STATIC_DIRECT_ERR_INVALID_SLICE;
        }
        slice->offset -= MINIRESNET_PATCH_REMAP_OLD_BIG_ACTUAL_BASE;
    }

    if (command_index < MINIRESNET_PATCH_REMAP_BIG_SUFFIX_END_COMMAND &&
        original_offset >= MINIRESNET_PATCH_REMAP_OLD_BIG_BINDING_OFFSET &&
        original_offset < MINIRESNET_PATCH_REMAP_OLD_BIG_ACTUAL_BASE) {
        return AI_STATIC_DIRECT_ERR_INVALID_SLICE;
    }

    return AI_STATIC_DIRECT_OK;
}

static void remap_big_suffix_constants(uint32_t *constants,
                                       uint32_t constant_count) {
    for (uint32_t i = 0; i < constant_count; ++i) {
        if (constants[i] >= MINIRESNET_PATCH_REMAP_OLD_BIG_INTERNAL_BASE &&
            constants[i] < MINIRESNET_PATCH_REMAP_OLD_BIG_BINDING_BYTES) {
            constants[i] -= MINIRESNET_PATCH_REMAP_OLD_BIG_INTERNAL_BASE;
        }
    }
}

static int invoke_one_remapped_command(
    const ai_static_direct_descriptor_t *descriptor,
    uint32_t command_index,
    const ai_static_direct_command_t *command,
    const iree_hal_executable_library_v0_t *library,
    const iree_hal_executable_environment_v0_t *environment,
    ai_static_direct_context_t *context) {
    ai_static_direct_command_t remapped_command = *command;
    ai_static_direct_dispatch_t remapped_dispatch;
    ai_static_direct_slice_t remapped_bindings
        [MINIRESNET_PATCH_REMAP_MAX_BINDINGS];
    uint32_t remapped_constants[MINIRESNET_PATCH_REMAP_MAX_CONSTANTS];
    int big_suffix_binding = 0;

    if (command->type == AI_STATIC_DIRECT_COMMAND_DISPATCH) {
        const ai_static_direct_dispatch_t *dispatch =
            command->config.dispatch.dispatch;
        if (dispatch == NULL) {
            return AI_STATIC_DIRECT_ERR_INVALID_DESCRIPTOR;
        }
        if (dispatch->binding_count > MINIRESNET_PATCH_REMAP_MAX_BINDINGS ||
            dispatch->constant_count > MINIRESNET_PATCH_REMAP_MAX_CONSTANTS) {
            return AI_STATIC_DIRECT_ERR_UNSUPPORTED_DISPATCH;
        }

        remapped_dispatch = *dispatch;
        for (uint32_t i = 0; i < dispatch->binding_count; ++i) {
            remapped_bindings[i] = dispatch->bindings[i];
            int rc = remap_arena_slice(&remapped_bindings[i],
                                       command_index,
                                       &big_suffix_binding);
            if (rc != AI_STATIC_DIRECT_OK) {
                return rc;
            }
        }
        for (uint32_t i = 0; i < dispatch->constant_count; ++i) {
            remapped_constants[i] = dispatch->constants[i];
        }
        if (big_suffix_binding) {
            remap_big_suffix_constants(remapped_constants,
                                       dispatch->constant_count);
        }

        remapped_dispatch.bindings = remapped_bindings;
        remapped_dispatch.constants = remapped_constants;
        remapped_command.config.dispatch.dispatch = &remapped_dispatch;
    } else if (command->type == AI_STATIC_DIRECT_COMMAND_FILL) {
        int rc = remap_arena_slice(&remapped_command.config.fill.target,
                                   command_index,
                                   &big_suffix_binding);
        if (rc != AI_STATIC_DIRECT_OK) {
            return rc;
        }
    }

    ai_static_direct_descriptor_t one_command_descriptor = *descriptor;
    one_command_descriptor.arena_bytes = MINIRESNET_PATCH_REMAP_ARENA_BYTES;
    one_command_descriptor.commands = &remapped_command;
    one_command_descriptor.command_count = 1u;
    int rc = ai_static_direct_invoke(&one_command_descriptor,
                                     library,
                                     environment,
                                     context);
    return rc;
}

int miniresnet_patch_invoke_continuation_remapped(
    const ai_static_direct_descriptor_t *descriptor,
    uint32_t command_start,
    const iree_hal_executable_library_v0_t *library,
    const iree_hal_executable_environment_v0_t *environment,
    ai_static_direct_context_t *context) {
    if (descriptor == NULL || descriptor->commands == NULL ||
        command_start > descriptor->command_count) {
        return AI_STATIC_DIRECT_ERR_INVALID_ARGUMENT;
    }

    for (uint32_t i = command_start; i < descriptor->command_count; ++i) {
        int rc = invoke_one_remapped_command(descriptor,
                                             i,
                                             &descriptor->commands[i],
                                             library,
                                             environment,
                                             context);
        if (rc != AI_STATIC_DIRECT_OK) {
            return rc;
        }
    }
    return AI_STATIC_DIRECT_OK;
}
