/**
 * @file hal_clic.c
 * @brief CLIC (Core-Local Interrupt Controller) driver for BE-U1000
 *
 * The BE-U1000 uses a CLIC interrupt controller instead of the standard
 * RISC-V PLIC. Key differences:
 * - mtvec mode = 0x3 (CLIC vectored mode)
 * - MTVT CSR (0x307) holds the vector table base
 * - Each interrupt has its own vector entry
 * - No claim/complete cycle — interrupts are auto-claimed on entry
 *
 * Timer (IRQ7) and software (IRQ3) interrupt sources are generated by CLINT,
 * but still need per-source enable/configuration in BE-U1000 CLIC.
 */

#include "hal_irq.h"
#include "hal_uart.h"
#include <stddef.h>
#include <stdint.h>

/* Maximum number of CLIC interrupt sources */
#define CLIC_MAX_IRQS   80

/* CLIC CSR definitions */
#define CSR_MTVT        0x307
#define CSR_MINTTHRESH  0x347

/* BE-U1000 CLIC register layout, aligned with the vendor SDK. */
#define CLIC_CFG_OFFSET             0x0000u
#define CLIC_INTIE_OFFSET           0x1001u
#define CLIC_INTATTR_OFFSET         0x1002u
#define CLIC_INTCTL_OFFSET          0x1003u
#define CLIC_IRQ_STRIDE             4u

#define CLIC_CFG_NLBITS_POS         1u
#define CLIC_CFG_NLBITS_MASK        (0x0Fu << CLIC_CFG_NLBITS_POS)
#define CLIC_CFG_NMBITS_POS         5u
#define CLIC_CFG_NMBITS_MASK        (0x03u << CLIC_CFG_NMBITS_POS)

#define CLIC_INTIE_IE               0x01u
#define CLIC_INTATTR_SHV_VECTORED   0x01u
#define CLIC_INTATTR_TRIG_LEVEL     0x00u
#define CLIC_INTATTR_TRIG_POSITIVE  0x00u
#define CLIC_INTATTR_MODE_MACHINE   0xC0u
#define CLIC_INTCTL_BITS            4u

#define CLIC_DEFAULT_NMBITS         1u
#define CLIC_DEFAULT_NLBITS         1u
#define CLIC_DEFAULT_LEVEL          1u
#define CLIC_DEFAULT_PRIORITY       1u
#define CLIC_MACHINE_TIMER_IRQ      7u

/* Interrupt handler table */
static hal_irq_handler_t clic_handlers[CLIC_MAX_IRQS];

/* CLIC base address for memory-mapped control registers. */
static uintptr_t clic_base;

static volatile uint8_t *clic_reg8(uint32_t offset)
{
    return (volatile uint8_t *)(clic_base + offset);
}

static uint32_t clic_irq_reg(uint32_t offset, uint32_t irq_num)
{
    return offset + (irq_num * CLIC_IRQ_STRIDE);
}

static void clic_write_mintthresh(uint32_t value)
{
    __asm__ volatile("csrw 0x347, %0" :: "r"(value));
}

static void clic_config_controller(uint8_t nmbits, uint8_t nlbits)
{
    uint8_t cfg = *clic_reg8(CLIC_CFG_OFFSET);

    cfg &= (uint8_t)~(CLIC_CFG_NMBITS_MASK | CLIC_CFG_NLBITS_MASK);
    cfg |= (uint8_t)(((nmbits << CLIC_CFG_NMBITS_POS) & CLIC_CFG_NMBITS_MASK) |
                     ((nlbits << CLIC_CFG_NLBITS_POS) & CLIC_CFG_NLBITS_MASK));
    *clic_reg8(CLIC_CFG_OFFSET) = cfg;
}

static uint8_t clic_get_nlbits(void)
{
    return (uint8_t)((*clic_reg8(CLIC_CFG_OFFSET) & CLIC_CFG_NLBITS_MASK) >>
                     CLIC_CFG_NLBITS_POS);
}

static uint8_t clic_make_intctl(uint32_t level, uint32_t priority)
{
    uint8_t nlbits = clic_get_nlbits();
    uint8_t intctl = 0u;

    if (nlbits > CLIC_INTCTL_BITS) {
        nlbits = CLIC_INTCTL_BITS;
    }

    if (nlbits > 0u) {
        uint32_t max_level = (1u << nlbits) - 1u;
        if (level > max_level) {
            level = max_level;
        }
        intctl = (uint8_t)(level << (8u - nlbits));
    }

    if (nlbits < CLIC_INTCTL_BITS) {
        uint32_t max_priority = (1u << (CLIC_INTCTL_BITS - nlbits)) - 1u;
        if (priority > max_priority) {
            priority = max_priority;
        }
        intctl |= (uint8_t)(priority << (8u - CLIC_INTCTL_BITS));
    }

    intctl |= (uint8_t)(0xFFu >> CLIC_INTCTL_BITS);
    return intctl;
}

static void clic_config_irq(uint32_t irq_num, uint32_t level, uint32_t priority)
{
    uint8_t attr = CLIC_INTATTR_MODE_MACHINE |
                   CLIC_INTATTR_TRIG_POSITIVE |
                   CLIC_INTATTR_TRIG_LEVEL |
                   CLIC_INTATTR_SHV_VECTORED;

    *clic_reg8(clic_irq_reg(CLIC_INTATTR_OFFSET, irq_num)) = attr;
    *clic_reg8(clic_irq_reg(CLIC_INTCTL_OFFSET, irq_num)) =
        clic_make_intctl(level, priority);
}

/* ============================================================================
 * CLIC Operations Implementation
 * ========================================================================= */

static void clic_init(os_ubase_t base)
{
    clic_base = (uintptr_t)base;

    /* Clear all handler registrations */
    for (int i = 0; i < CLIC_MAX_IRQS; i++) {
        clic_handlers[i] = NULL;
    }

    if (clic_base == 0u) {
        return;
    }

    clic_config_controller(CLIC_DEFAULT_NMBITS, CLIC_DEFAULT_NLBITS);
    clic_write_mintthresh(0u);
    clic_config_irq(CLIC_MACHINE_TIMER_IRQ,
                    CLIC_DEFAULT_LEVEL,
                    CLIC_DEFAULT_PRIORITY);
    *clic_reg8(clic_irq_reg(CLIC_INTIE_OFFSET, CLIC_MACHINE_TIMER_IRQ)) |=
        CLIC_INTIE_IE;
}

static void clic_enable(uint32_t irq_num)
{
    if (irq_num >= CLIC_MAX_IRQS) return;

    if (clic_base) {
        volatile uint8_t *clicintie = clic_reg8(clic_irq_reg(CLIC_INTIE_OFFSET, irq_num));
        volatile uint8_t *clicintctl = clic_reg8(clic_irq_reg(CLIC_INTCTL_OFFSET, irq_num));

        *clic_reg8(clic_irq_reg(CLIC_INTATTR_OFFSET, irq_num)) =
            CLIC_INTATTR_MODE_MACHINE |
            CLIC_INTATTR_TRIG_POSITIVE |
            CLIC_INTATTR_TRIG_LEVEL |
            CLIC_INTATTR_SHV_VECTORED;
        if (*clicintctl == 0u) {
            *clicintctl = clic_make_intctl(CLIC_DEFAULT_LEVEL,
                                           CLIC_DEFAULT_PRIORITY);
        }
        *clicintie |= CLIC_INTIE_IE;
    }
}

static void clic_disable(uint32_t irq_num)
{
    if (irq_num >= CLIC_MAX_IRQS) return;

    if (clic_base) {
        volatile uint8_t *clicintie = clic_reg8(clic_irq_reg(CLIC_INTIE_OFFSET, irq_num));
        *clicintie &= (uint8_t)~CLIC_INTIE_IE;
    }
}

static void clic_set_priority(uint32_t irq_num, uint32_t priority)
{
    if (irq_num >= CLIC_MAX_IRQS) return;

    if (clic_base) {
        volatile uint8_t *clicintctl = clic_reg8(clic_irq_reg(CLIC_INTCTL_OFFSET, irq_num));
        *clicintctl = clic_make_intctl(CLIC_DEFAULT_LEVEL, priority);
    }
}

static uint32_t clic_claim(uint32_t hart)
{
    (void)hart;
    /*
     * In CLIC mode, the interrupt number is automatically determined
     * by the hardware and delivered via the vector table. The trap
     * handler reads mcause to get the IRQ number.
     *
     * This function is called from trap.c with the mcause-derived
     * IRQ number already known. We return 0 here as a no-op.
     * The actual dispatch is done via clic_dispatch().
     */
    return 0;
}

static void clic_complete(uint32_t hart, uint32_t irq_num)
{
    (void)hart;
    (void)irq_num;
    /*
     * CLIC auto-completes interrupts. No acknowledge cycle needed
     * (unlike PLIC claim/complete). This is a no-op.
     */
}

static void clic_register_handler(uint32_t irq_num, hal_irq_handler_t handler)
{
    if (irq_num < CLIC_MAX_IRQS) {
        clic_handlers[irq_num] = handler;
    }
}

/* ============================================================================
 * CLIC dispatch — called from trap handler for external interrupts
 * ========================================================================= */

/**
 * Dispatch a CLIC interrupt to the registered handler.
 * Called from os_trap_handler() when an external interrupt arrives.
 *
 * @param irq_num The interrupt number from mcause[9:0]
 */
void hal_clic_dispatch(uint32_t irq_num)
{
    if (irq_num < CLIC_MAX_IRQS && clic_handlers[irq_num]) {
        clic_handlers[irq_num](irq_num);
    } else {
        os_print("[CLIC] Unhandled IRQ %d\n", irq_num);
    }
}

/* ============================================================================
 * CLIC ops vtable
 * ========================================================================= */

static const hal_irq_ops_t clic_ops = {
    .init           = clic_init,
    .enable         = clic_enable,
    .disable        = clic_disable,
    .set_priority   = clic_set_priority,
    .claim          = clic_claim,
    .complete       = clic_complete,
    .register_handler = clic_register_handler,
    .type           = HAL_IRQ_TYPE_CLIC,
};

/* ============================================================================
 * Public initialization
 * ========================================================================= */

/* g_irq_ops defined here for BE-U1000 (hal_plic_irq.c is excluded from this build) */
const hal_irq_ops_t *g_irq_ops = (void *)0;

void hal_irq_init_clic(os_ubase_t base)
{
    g_irq_ops = &clic_ops;
    clic_init(base);
}
