#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
IREE_SOURCE_DIR="${IREE_SOURCE_DIR:-${PROJECT_ROOT}/third_party/iree}"
IREE_LOCAL_COMPILER_BUILD_DIR="${IREE_LOCAL_COMPILER_BUILD_DIR:-${PROJECT_ROOT}/build/iree-compiler-local}"
IREE_LOCAL_COMPILER_JOBS="${IREE_LOCAL_COMPILER_JOBS:-$(nproc)}"
IREE_LOCAL_COMPILER_CC="${IREE_LOCAL_COMPILER_CC:-/usr/bin/clang}"
IREE_LOCAL_COMPILER_CXX="${IREE_LOCAL_COMPILER_CXX:-/usr/bin/clang++}"
IREE_LOCAL_COMPILER_CPU_TARGETS="${IREE_LOCAL_COMPILER_CPU_TARGETS:-X86;RISCV}"
IREE_LOCAL_COMPILER_RISCV32_UKERNEL_ABI="${IREE_LOCAL_COMPILER_RISCV32_UKERNEL_ABI:-ilp32f}"
IREE_LOCAL_COMPILER_RISCV32_UKERNEL_MARCH="${IREE_LOCAL_COMPILER_RISCV32_UKERNEL_MARCH:-rv32imafc_zifencei_zicsr}"

echo "Initializing IREE compiler submodules..."
git -C "${IREE_SOURCE_DIR}" submodule update --init --depth=1 third_party/llvm-project

if [[ -f "${IREE_LOCAL_COMPILER_BUILD_DIR}/CMakeCache.txt" ]] && \
   ! grep -Eq "^CMAKE_C_COMPILER:[^=]+=${IREE_LOCAL_COMPILER_CC}$" "${IREE_LOCAL_COMPILER_BUILD_DIR}/CMakeCache.txt"; then
  echo "Removing stale local compiler build cache with a different host C compiler."
  rm -rf "${IREE_LOCAL_COMPILER_BUILD_DIR}"
fi

echo "Configuring local IREE compiler build: ${IREE_LOCAL_COMPILER_BUILD_DIR}"
cmake -S "${IREE_SOURCE_DIR}" -B "${IREE_LOCAL_COMPILER_BUILD_DIR}" -G Ninja \
  -DCMAKE_C_COMPILER="${IREE_LOCAL_COMPILER_CC}" \
  -DCMAKE_CXX_COMPILER="${IREE_LOCAL_COMPILER_CXX}" \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DIREE_BUILD_COMPILER=ON \
  -DIREE_BUILD_TESTS=OFF \
  -DIREE_BUILD_SAMPLES=OFF \
  -DIREE_BUILD_PYTHON_BINDINGS=OFF \
  -DIREE_ENABLE_WERROR_FLAG=OFF \
  -DIREE_BUILD_BUNDLED_LLVM=ON \
  -DIREE_DEFAULT_CPU_LLVM_TARGETS="${IREE_LOCAL_COMPILER_CPU_TARGETS}" \
  -DIREE_UKERNEL_BITCODE_RISCV32_ABI="${IREE_LOCAL_COMPILER_RISCV32_UKERNEL_ABI}" \
  -DIREE_UKERNEL_BITCODE_RISCV32_MARCH="${IREE_LOCAL_COMPILER_RISCV32_UKERNEL_MARCH}" \
  -DCLANG_ENABLE_ARCMT=OFF \
  -DCLANG_ENABLE_STATIC_ANALYZER=OFF \
  -DIREE_HAL_DRIVER_DEFAULTS=OFF \
  -DIREE_HAL_DRIVER_VULKAN=OFF \
  -DIREE_HAL_DRIVER_CUDA=OFF \
  -DIREE_HAL_DRIVER_HIP=OFF \
  -DIREE_HAL_DRIVER_LOCAL_SYNC=ON \
  -DIREE_HAL_DRIVER_LOCAL_TASK=ON \
  -DIREE_TARGET_BACKEND_DEFAULTS=OFF \
  -DIREE_TARGET_BACKEND_LLVM_CPU=ON \
  -DIREE_TARGET_BACKEND_VMVX=ON \
  -DIREE_INPUT_STABLEHLO=OFF \
  -DIREE_INPUT_TORCH=OFF \
  -DIREE_INPUT_TOSA=ON \
  -DIREE_OUTPUT_FORMAT_C=ON \
  -DIREE_ERROR_ON_MISSING_SUBMODULES=OFF

echo "Building local IREE compiler tools..."
cmake --build "${IREE_LOCAL_COMPILER_BUILD_DIR}" \
  --target iree-compile iree-opt \
  --parallel "${IREE_LOCAL_COMPILER_JOBS}"

TOOLS_DIR="${IREE_LOCAL_COMPILER_BUILD_DIR}/tools"
"${TOOLS_DIR}/iree-compile" --version
"${TOOLS_DIR}/iree-opt" --version

cat <<EOF

Local IREE compiler tools are ready.
Use them with:

  export IREE_LOCAL_COMPILER_ROOT=${TOOLS_DIR}

EOF
